# 日志记录配置
logging:
  config:
    classpath:logback-spring.xml
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

# 数据源配置(HikariCP)
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/mmall_learning?serverTimezone=UTC&characterEncoding=utf-8
    username: 数据库账号
    password: 数据库密码
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 3000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateBookHikariCP
      max-lifetime: 28740000
      connection-test-query: SELECT 1

# Mybatis配置
mybatis:
  mapper-locations: /mappers/*.xml
  type-aliases-package: com.chen.mmall.dao

# 端口
server:
  port: 8088
